### ISSUE TITLE
Parsing multiple pages

### ISSUE THREAD

**Issue by loughnane** [kellerjustin/rest-uploader#1]
Firstly, I love this. It was the big thing I was missing from Evernote.

One issue I see is that when I upload a multi-page PDF it seems to only scan and parse the first page. Is that expected behavior?

- Windows 10

**Comment by loughnane** [comment]
I think i figured it out. Created a pull request with the fix. 

https://github.com/kellerjustin/rest-uploader/pull/2

**Comment by cerealkella** [comment]
Sorry, @loughnane, just seeing this today. Thanks!
Someone else had a note about the OCR functionality on the joplin forum, which prompted me to review my code... unless I'm missing something, I think the closing comment tag also needs to be outside the loop. I'll merge your PR, do a bit of testing and maybe add pagination in the function - to denote PAGE X of Y.
Thanks again!

**Comment by cerealkella** [comment]
Okay, this has been fixed.

The OCR on the first page was sort of a "known bug" -- I initially programmed it to extract embedded PDF text if available or just use the preview image and OCR if no embedded text. I modified the code to extract text from all pages. If you're dropping in large PDFs, be aware that this will definitely take longer to process.

Thanks for the feedback!
